version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkusdb
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data: